{% set name = "geosnap" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5da4fa6bdfdafcced0280adaae70dd22c6bcf89292a2c4661084bf2887eff00

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - versioneer
  run:
    - python >=3
    - pandas
    - giddy >=2.2.1
    - libpysal
    - spenc
    - cenpy >=1.0
    - geopandas
    - matplotlib-base
    - scikit-learn
    - seaborn
    - pyarrow >=0.14.1
    - appdirs
    - dash
    - dash-bootstrap-components
    - palettable
    - pip
    - tqdm
    - quilt3 >=3.1.11
    - xlrd
    - mapclassify
    - region >=0.2.0
    - tobler >=0.8.2
    - scikit-plot
    - contextily
    - proplot >=0.9
    - spopt >=0.1.1
    - fsspec
    - s3fs
    - versioneer
    - segregation >=2.1

test:
  imports:
    - geosnap

about:
  home: http://github.com/spatialucr/geosnap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Geospatial Neighborhood Analysis in Python

  description: |
    geosnap is an open-source, Python package for exploring, modeling, and visualizing neighborhood 
    dynamics. It provides a suite of tools for creating socio-spatial datasets, harmonizing those 
    datasets into consistent set of time-static boundaries, and modeling neighborhood change using 
    classic and spatial statistical methods.
  doc_url: http://spatialucr.github.io/geosnap
  dev_url: https://github.com/spatialucr/geosnap

extra:
  recipe-maintainers:
    - knaaptime
    - sjsrey
