{% set name = "geosnap" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2fab6b91dc89fad088fb7ea7408b1dbf2d1211c1cd2ffaa4184fa5bddc5dc253

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - versioneer
  run:
    - python >=3
    - pandas
    - giddy >=2.2.1
    - libpysal
    - spenc
    - cenpy >=1.0
    - geopandas
    - matplotlib-base
    - scikit-learn
    - seaborn
    - pyarrow >=0.14.1
    - appdirs
    - dash
    - dash-bootstrap-components
    - palettable
    - pip
    - tqdm
    - quilt3 >=3.1.11
    - xlrd
    - region >=0.2.0
    - tobler >=0.2.1
    - scikit-plot
    - contextily
    - proplot
    - spopt >=0.1.1
    - fsspec
    - s3fs
    - botocore >=1.20.21
    - versioneer
    - segregation >=2.1

test:
  imports:
    - geosnap

about:
  home: http://github.com/spatialucr/geosnap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Geospatial Neighborhood Analysis in Python

  description: |
    geosnap is an open-source, Python package for exploring, modeling, and visualizing neighborhood 
    dynamics. It provides a suite of tools for creating socio-spatial datasets, harmonizing those 
    datasets into consistent set of time-static boundaries, and modeling neighborhood change using 
    classic and spatial statistical methods.
  doc_url: http://spatialucr.github.io/geosnap
  dev_url: https://github.com/spatialucr/geosnap

extra:
  recipe-maintainers:
    - jGaboardi
    - knaaptime
    - sjsrey
